In [1]:
import numpy as np
import MaxLik as ML

## Import of conversions relations

### Sigma matrices

In [2]:
sigma1 = np.array([[1., 0.], [0., -1.]])
sigma2 = np.array([[0., 1.], [1., 0.]])
sigma3 = np.array([[0., -1j], [1j, 0.]])
sigma = np.array([sigma1, sigma2, sigma3])

### Convert rho matrix to Bloch vector

In [3]:
blochFromRho = lambda rho_ : np.real(np.array([
    np.trace(np.dot(rho_,sigma1)),
    np.trace(np.dot(rho_,sigma2)),
    np.trace(np.dot(rho_,sigma3))
]))

# Data import

In [4]:
f = open('20200211_09h17min_HVDARL_Sample_dataset.txt')
dataRAW = []
for line in f.readlines():
    dataRAW.append(line.strip().split(',\t'))

In [5]:
# data formating
strList = []
for i in range (0,7):
    strList.extend(dataRAW[i][0].strip().replace('[', '').replace(']', '').replace('(', '').replace(')', '').replace(' ', ''))
str1 = ''.join(strList)

## Import TNLCd projectors from file

In [6]:
projRaw = str1.split('array')[1:7]

In [7]:
projectors = []
for i in range(0,6):
    myArray = np.array([[complex(projRaw[i].split(',')[0]),complex(projRaw[i].split(',')[1])],[complex(projRaw[i].split(',')[2]),complex(projRaw[i].split(',')[3])]])
    projectors.append(myArray)

In [8]:
projectors

[array([[2.06232435e-04+0.j        , 2.34509528e-03-0.01414858j],
        [2.34509528e-03+0.01414858j, 9.99793768e-01+0.j        ]]),
 array([[ 9.99566018e-01+0.j        , -4.21507759e-03-0.02035939j],
        [-4.21507759e-03+0.02035939j,  4.33981725e-04+0.j        ]]),
 array([[0.50221957+0.j        , 0.00070364+0.49754503j],
        [0.00070364-0.49754503j, 0.49778043+0.j        ]]),
 array([[ 0.49878551+0.j        , -0.49954608-0.02015359j],
        [-0.49954608+0.02015359j,  0.50121449+0.j        ]]),
 array([[0.50303306+0.j        , 0.49975206-0.01520001j],
        [0.49975206+0.01520001j, 0.49696694+0.j        ]]),
 array([[ 0.48383912+0.j        , -0.01067191-0.49821652j],
        [-0.01067191+0.49821652j,  0.51616088+0.j        ]])]

## Import measured data

In [9]:
countData = [float(dataRAW[i][1]) for i in range (7,13)]

In [10]:
print(countData)

[0.0006465315818786621, 4.008024966716766, 2.026712429523468, 1.941301190853119, 1.9922939896583558, 1.8951233506202698]


# Maximum-likelihood
State reconstruction using MaxLik

In [11]:
[rho,bloch] = ML.Maxlik(countData, projectors)

In [12]:
print ('Analyzed state: ' + str(bloch))

Analyzed state: [ 0.99951192 -0.00311421  0.03108417]


# All data reconstruction
Lets perform MaxLik reconstruction for all measured data

In [13]:
# import all data
dataAll = np.array(dataRAW[7:-1]).transpose()[1].reshape(6,6,1).astype(np.float)

In [14]:
#perform ML recosntruction
rhos = np.array([ML.Maxlik(countData, projectors)[0] for countData in dataAll])

In [15]:
[blochFromRho(rho) for rho in rhos]

[array([ 0.99951192, -0.00311421,  0.03108417]),
 array([-0.99957249, -0.01209158,  0.02662003]),
 array([0.00928819, 0.9996032 , 0.02659264]),
 array([-0.00505469, -0.99949419,  0.03139767]),
 array([ 0.03062416, -0.00217134,  0.99952861]),
 array([ 5.01885615e-02, -1.95181750e-04, -9.97459078e-01])]